# Generated by Django 2.2 on 2019-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cleanup_after', models.DateTimeField()),
            ],
        ),
    ]
